apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-iuya
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-iuya@sha256:7e9e468a0ca3d37a5f71a10a59f6f0534223d9f9444ba9ee372c890288c141c0
        name: my-nodejs
        resources: {}
status: {}
